#! /usr/bin/env sh

[ -f /sbin/functions.sh ] && source /sbin/functions.sh || source /lib/rc/sh/functions.sh

ebegin "Mise a jour de l'arbre de portage Layman"

/usr/bin/layman -S &&

ebegin "Liste le portage Layman"

/usr/bin/layman -L &&

ebegin "Mise a jour de l'arbre de portage"

/usr/bin/emerge --sync &&

ebegin "Mise a jour de portage"

/usr/bin/emerge portage &&

ebegin "Mise a jour de world"

/usr/bin/emerge -avuDN world &&

ebegin "Mise a jour de la databse eix"

/usr/bin/update-eix

